-- database.sql
-- ================================================
-- Script SQL - Quiz2_KevinDuarte
-- Base de datos Oracle (SQLplus)
-- ================================================

-- Eliminar tablas si existen (en orden por FK)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE servicios CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE cliente CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ================================================
-- Tabla CLIENTE
-- ================================================
CREATE TABLE cliente (
    id_cliente     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre         VARCHAR2(80)  NOT NULL,
    correo         VARCHAR2(100),
    telefono       VARCHAR2(20),
    direccion      VARCHAR2(150),
    fecha_registro DATE DEFAULT SYSDATE
);

-- ================================================
-- Tabla SERVICIOS
-- ================================================
CREATE TABLE servicios (
    id_servicio  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR2(80)   NOT NULL,
    descripcion  VARCHAR2(200),
    precio       NUMBER(10, 2)  DEFAULT 0,
    disponible   CHAR(1)        DEFAULT 'S' CHECK (disponible IN ('S', 'N')),
    id_cliente   NUMBER,
    CONSTRAINT fk_servicio_cliente
        FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente)
        ON DELETE SET NULL
);

-- ================================================
-- Datos de prueba
-- ================================================
INSERT INTO cliente (nombre, correo, telefono, direccion)
VALUES ('Juan Perez', 'juan@mail.com', '3001234567', 'Calle 10 #5-20');

INSERT INTO cliente (nombre, correo, telefono, direccion)
VALUES ('Maria Lopez', 'maria@mail.com', '3109876543', 'Carrera 15 #8-45');

INSERT INTO servicios (nombre, descripcion, precio, id_cliente)
VALUES ('Mantenimiento PC', 'Revisión y limpieza de equipo', 80000, 1);

INSERT INTO servicios (nombre, descripcion, precio, id_cliente)
VALUES ('Diseño Web', 'Página web empresarial', 350000, 2);

COMMIT;
